package shiv.com.jemtec;

import android.app.Activity;
import android.os.Bundle;
import android.webkit.WebView;


public class NewActivity2 extends Activity {
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.newactivity_2);
        WebView tv2= (WebView) findViewById(R.id.webview2);
        String text2 = "<html><body style=\"text-align:justify\"> %s </body></Html>";
        String data2="<u>IPU Counselling</u><br>Students must note that only those students, who have qualified in IPU CET 2015, can apply for the IPU CET 2015 Counseling. Candidates can check the IPU CET Counseling Procedure and the counselling Schedules for B.Tech at techbits.co.in .<br><br> IPU CET 2015 Counselling Details:<br>Registration:<br> 1. Counselling Fee Payment: <br> IPU CET 2015 Registration Fees: Rs.1000 (non refundable)<br> IPU CET 2015 Payment mode: <br>1. Net banking<br>2. Credit/Debit Card<br> 3. Candidates can download and print the Indian Bank Challan. (Registration will be only done two days after the payment is made) <br>Cash payment has to be made by the candidate at any Indian Bank branch.<br> Note: The Bank Challan copy has to be kept for further reference.<br><br> IPU CET 2015 Registration Form: <br>1)Candidates can log in entering their IPU CET 2015 Roll Number, Date of Birth and Mobile Number.<br>n2) Candidates have to fill in the Bank Reference no (transaction ID/Challan No.) in the online form after payment of the registration fees.<br>3) After authentication, candidates will have to fill in their particulars- personal, academic, contact details with address, mobile No. and Email ID.<br>4) They must choose a password as per specifications mentioned therein.<br><br> Choice Filling: <br>1)Candidates must log in using their course, CET 2015 Roll No. and password chosen during registration.<br>2) Candidates must fill their choices as per their course preferences.<br>3) They must fill the maximum number of options to ensure that they avail a seat of their preference.<br>4) There is no restriction on the number of options that can be filled by a candidate.<br> <br>Verification of Documents:<br> After registration it is mandatory for all candidates who have registered in aany reserved category(except OBC)to report physically at the designated centres as per the GGSIPU(list of designated centres shall be uploaded on university websites before the start of Counselling.<br>Candidates who fail to report at any of the designated centres would not be considered in special category.<br><br>Allocation of Seats:<br><br>" +
                "1.Allocation of seats in round(01):<br><br>Candidates satisfied with their allotment can print the provisional allotment letter available on your account login during registration process and pay the part academic fees of Rs.40,000 through cash(through challan and paying the cash in any Indian bank branch) or through Net banking.<br>After allotment and payment of part academic fee candidates will have to report to the designated centres of GGSIPU with the academic fee receipt and all required documents with the necessary record of verification of reserved category.<br><br>2.Freezing of Allotment : If the candidate is satisfied with his allotment he can press the freeze button else in the subsequent rounds next higher preferences will be altted to him.<br><br>3.Withdrawal after round 01 :<br>Allotment and payment of fess ,Candidates can withdraw their fees (Rs.40,000)by pressing withdrawal button available on admission website after login but,after that the candidate wouldn't be considered for allotment in subsequent rounds except Spot Counselling.<br><br>4.Result of round 02 allotment:<br>Candidates who will be alloted seats are:-<br>1.Candidates who have registered filled choices and not allotted seat in round 01.<br>2.Candidates who have been allotted seat in round 01, reported to the designated centres ,paid the fees but didn't freeze the allotted seat and neither withdrawn the fees.<br><br>After round 01 Candidates will be able to modify and edit their choices and preferences :<br> 1.All candidates who have been allotted seat in this round only will have to print the provisional letter , pay the part academic fee and report to the designated centre for verification of documents.<br>2.The Candidates who have paid the fees in round 01 but didn't freeze,will have to print the fresh provisional letter and part academic fee receipt with amended name of institute/College (they don't need to appear for verification of documents again if already appeared in round 01).<br>3.Candidates can apply for withdrawal of fees in second round also.<br>4.After allotment, payment and verification ,Candidates can print the Provisional admission slip and join the respective College.";
        tv2.loadData(String.format(text2, data2), "text/html", "utf-8");
    }
}
